import { defaultLocale, type Locale } from '@/lib/translations'

const ministrySources = {
  categories: 'https://www.inclusion.gob.es/en/web/unidadgrandesempresas/autorizaciones-y-requisitos',
  nomadFaq: 'https://www.inclusion.gob.es/en/web/unidadgrandesempresas/teletrabajadores',
  nomadHolder:
    'https://www.inclusion.gob.es/documents/d/unidadgrandesempresas/informacion-documentacion-pagina-web-titular-v2',
  nomadFamily:
    'https://www.inclusion.gob.es/documents/d/unidadgrandesempresas/informacion-documentacion-pagina-web-familiares-v2',
  orientation:
    'https://www.inclusion.gob.es/en/web/unidadgrandesempresas/documentacion-orientativa',
}

const content = {
  es: {
    categories: {
      eyebrow: 'Autorizaciones UGE',
      title: 'Categorías oficiales para vivir y trabajar en España',
      subtitle:
        'Mostramos las vías oficiales de la Unidad de Grandes Empresas. Nomad ya está detallado; el resto queda visible para orientar al usuario.',
      availableNow: 'Disponible ahora',
      comingSoon: 'Próximamente',
      exploreNomad: 'Explorar Nomad',
      cards: {
        entrepreneurs: {
          title: 'Emprendedores',
          description: 'Para proyectos empresariales innovadores con interés económico para España.',
        },
        highly_qualified: {
          title: 'Profesionales altamente cualificados',
          description: 'Para contratación especializada y tarjeta azul UE.',
        },
        researchers: {
          title: 'Investigadores',
          description: 'Para actividades de I+D+i y movilidad investigadora.',
        },
        ict: {
          title: 'Movilidad intraempresarial',
          description: 'Traslado internacional dentro del mismo grupo empresarial.',
        },
        collective_ict: {
          title: 'ICT colectiva',
          description: 'Procedimiento colectivo para grupos de traslados intraempresariales.',
        },
        audiovisual: {
          title: 'Audiovisual y cultural',
          description: 'Producciones del sector audiovisual y actividades culturales estratégicas.',
        },
        nomad: {
          title: 'Nomad',
          description: 'Teletrabajo internacional con empresa o clientes fuera de España.',
        },
        family: {
          title: 'Familiares',
          description: 'Familiares de titulares bajo Ley 14/2013 con requisitos de vínculo y dependencia.',
        },
        legacy: {
          title: 'Caso heredado',
          description: 'Expediente migrado desde el modelo anterior de la plataforma.',
        },
      },
    },
    tracks: {
      legacy_general: {
        title: 'Caso heredado',
        shortTitle: 'Heredado',
        description: 'Expediente migrado desde la versión anterior.',
      },
      nomad_holder: {
        title: 'Teletrabajo internacional - solicitante principal',
        shortTitle: 'Principal',
        description: 'Solicitud inicial de la persona titular que teletrabaja para empresa o clientes fuera de España.',
      },
      nomad_family: {
        title: 'Teletrabajo internacional - familiares',
        shortTitle: 'Familiares',
        description: 'Caso separado para familiares del titular, con su propia documentación y seguimiento.',
      },
      nomad_renewal: {
        title: 'Teletrabajo internacional - renovación',
        shortTitle: 'Renovación',
        description: 'Renovación independiente vinculada a una autorización previa de teletrabajo internacional.',
      },
    },
    caseStages: {
      intake: 'Apertura del caso',
      eligibility_check: 'Revisión inicial',
      lawyer_review: 'Revisión legal',
      documents_required: 'Documentos requeridos',
      payment_pending: 'Pago pendiente',
      ready_to_file: 'Listo para presentar',
      submitted: 'Presentado',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      closed: 'Cerrado',
    },
    outcomes: {
      pending: 'Pendiente',
      approved: 'Aprobado',
      rejected: 'Rechazado',
      withdrawn: 'Retirado',
      expired: 'Caducado',
      renewed: 'Renovado',
    },
    paymentStatuses: {
      not_needed: 'No necesario',
      pending: 'Pendiente',
      requested: 'Solicitado',
      paid: 'Pagado',
      waived: 'Condonado',
    },
    paymentMilestones: {
      consultation: 'Consulta',
      case_opening: 'Apertura de caso',
      filing: 'Presentación',
      renewal: 'Renovación',
    },
    nomadPage: {
      title: 'Nomad para España',
      subtitle:
        'Dividimos Nomad en tres procesos distintos para que inmigrante y abogado no mezclen requisitos, pagos ni documentos.',
      cards: {
        nomad_holder: 'Soy la persona solicitante principal',
        nomad_family: 'Quiero abrir un caso para familiares',
        nomad_renewal: 'Necesito renovar un caso Nomad',
      },
      summaryTitle: 'Qué separa estos tres procesos',
      summaryBullets: [
        'Solicitante principal: relación con empresa extranjera, elegibilidad principal y expediente base.',
        'Familiares: vínculo y dependencia, con documentación y pagos propios.',
        'Renovación: nuevo caso enlazado al expediente previo, nunca un cambio de estado dentro del caso original.',
      ],
      holderTitle: 'Solicitante principal',
      holderBullets: [
        'Pasaporte completo, tasa y formulario.',
        'Relación laboral o profesional mínima de 3 meses.',
        'Actividad real y continuada de la empresa extranjera durante al menos 1 año.',
        'Carta autorizando el trabajo remoto desde España.',
        'Ingresos suficientes, titulación o 3 años de experiencia, seguridad social o seguro, y antecedentes penales.',
      ],
      familyTitle: 'Familiares',
      familyBullets: [
        'Cónyuge/pareja, hijos o ascendientes dependientes con prueba documental del vínculo.',
        'Dependencia económica o física cuando corresponda.',
        'Recursos económicos suficientes vinculados al titular.',
        'Caso separado para poder gestionar documentos, pagos y estado sin contaminar el expediente principal.',
      ],
      renewalTitle: 'Renovación',
      renewalBullets: [
        'Se abre como un nuevo caso enlazado al expediente Nomad anterior.',
        'Debe acreditar continuidad de la relación profesional o laboral, medios económicos y cumplimiento mantenido.',
        'Se usa también cuando el usuario necesita reordenar documentos, nuevo pago o estrategia distinta con el abogado.',
      ],
      faqTitle: 'Reglas operativas que el producto debe mostrar',
      faqBullets: [
        'En relación profesional, el trabajo con clientes españoles no puede superar el 20 % de la actividad total.',
        'En relación laboral, el trabajo sigue vinculado a la empresa extranjera.',
        'Los familiares pueden tramitar autorización propia y trabajar en España si cumplen los requisitos.',
      ],
      sources: ministrySources,
    },
    immigrantDashboard: {
      title: 'Tus casos',
      subtitle: 'Gestiona varios procesos sin perder el historial anterior.',
      activeCases: 'Casos activos',
      pastCases: 'Casos anteriores',
      noCases: 'Todavía no has abierto ningún caso.',
      noCasesBody: 'Empieza con solicitante principal, familiares o renovación.',
      startNewCase: 'Crear nuevo caso',
      openCases: 'Ver casos',
      documents: 'Documentos recientes',
      pendingRequest: 'Solicitud de abogado',
    },
    immigrantCases: {
      title: 'Mis casos',
      subtitle: 'Cada caso tiene su propio abogado, pagos, documentos y línea temporal.',
      openNew: 'Crear nuevo caso',
      activeSection: 'Activos',
      archivedSection: 'Historial',
      emptyActive: 'No tienes casos activos.',
      emptyArchived: 'Todavía no hay casos cerrados o resueltos.',
      viewCase: 'Ver caso',
      relatedTo: 'Relacionado con',
      lawyerPending: 'Sin abogado asignado',
    },
    newCase: {
      title: 'Crear nuevo caso',
      subtitle: 'Elige el proceso adecuado de teletrabajo internacional y abre un expediente independiente.',
      trackLabel: 'Tipo de caso',
      summaryLabel: 'Contexto del caso',
      summaryPlaceholder:
        'Ejemplo: intento previo de estudiante rechazado, ahora quiero aplicar como teletrabajador internacional.',
      linkedCaseLabel: 'Caso vinculado',
      linkedCasePlaceholder: 'Selecciona un caso previo cuando aplique',
      submit: 'Crear caso',
      creating: 'Creando caso...',
      success: 'Caso creado correctamente.',
      error: 'No se pudo crear el caso.',
    },
    caseDetail: {
      overview: 'Resumen',
      documents: 'Documentos',
      payments: 'Pagos',
      timeline: 'Historial',
      opened: 'Abierto',
      lawyer: 'Abogado',
      linkedHistory: 'Historial vinculado',
      requestLawyer: 'Elegir abogado para este caso',
      noLawyer: 'Sin abogado asignado todavía',
      noDocuments: 'Todavía no hay documentos en este caso.',
      noPayments: 'No hay hitos de pago todavía.',
      noEvents: 'Todavía no hay eventos en la línea temporal.',
      relatedCase: 'Caso vinculado',
      sourceCase: 'Caso de origen',
      deleteCase: 'Eliminar caso',
      deleting: 'Eliminando caso...',
      deleteConfirm: '¿Seguro que quieres eliminar este caso? También se borrarán sus documentos, pagos e historial.',
      deleteError: 'No se pudo eliminar el caso.',
      privateNotes: 'Notas privadas',
      privateNotesPlaceholder: 'Añade una nota solo visible para el abogado en este caso...',
      saveNote: 'Guardar nota',
      savingNote: 'Guardando nota...',
      noPrivateNotes: 'Todavía no hay notas privadas.',
    },
    lawyerDashboard: {
      title: 'Casos del despacho',
      subtitle: 'Ahora el trabajo se organiza por caso, no por persona.',
      assignedCases: 'Casos asignados',
      pendingRequests: 'Solicitudes pendientes',
      readyToFile: 'Listos para presentar',
      recentCases: 'Casos recientes',
    },
    lawyerCases: {
      title: 'Casos',
      subtitle: 'Gestiona solicitante principal, familiares y renovación de forma independiente.',
      empty: 'No tienes casos asignados.',
      caseOwner: 'Cliente',
      stage: 'Etapa',
      track: 'Track',
      opened: 'Abierto',
      viewCase: 'Abrir caso',
    },
    lawyerRequests: {
      caseLabel: 'Caso',
      linkedTrack: 'Track solicitado',
    },
  },
  en: {
    categories: {
      eyebrow: 'UGE authorizations',
      title: 'Official categories to live and work in Spain',
      subtitle:
        'We surface the official Large Companies Unit pathways. Nomad is detailed now; the others stay visible for guidance.',
      availableNow: 'Available now',
      comingSoon: 'Coming soon',
      exploreNomad: 'Explore Nomad',
      cards: {
        entrepreneurs: {
          title: 'Entrepreneurs',
          description: 'For innovative business projects with economic interest for Spain.',
        },
        highly_qualified: {
          title: 'Highly qualified professionals',
          description: 'For specialized hiring and EU Blue Card routes.',
        },
        researchers: {
          title: 'Researchers',
          description: 'For R&D and research mobility cases.',
        },
        ict: {
          title: 'Intra-company transfer',
          description: 'International transfers inside the same corporate group.',
        },
        collective_ict: {
          title: 'Collective ICT',
          description: 'Collective procedure for batches of intra-company transfers.',
        },
        audiovisual: {
          title: 'Audiovisual and cultural',
          description: 'Strategic audiovisual productions and cultural activity cases.',
        },
        nomad: {
          title: 'Nomad',
          description: 'International remote work with a foreign employer or foreign clients.',
        },
        family: {
          title: 'Family members',
          description: 'Family permits under Law 14/2013 with relationship and dependency rules.',
        },
        legacy: {
          title: 'Legacy case',
          description: 'Case migrated from the previous platform model.',
        },
      },
    },
    tracks: {
      legacy_general: { title: 'Legacy case', shortTitle: 'Legacy', description: 'Migrated from the previous product model.' },
      nomad_holder: { title: 'International telework - main applicant', shortTitle: 'Main applicant', description: 'Initial filing for the principal applicant working remotely for a foreign company or foreign clients.' },
      nomad_family: { title: 'International telework - family members', shortTitle: 'Family', description: 'Separate case for family members linked to the main applicant, with its own evidence and follow-up.' },
      nomad_renewal: { title: 'International telework - renewal', shortTitle: 'Renewal', description: 'Separate renewal case linked to a previous international telework authorization.' },
    },
    caseStages: {
      intake: 'Case opened',
      eligibility_check: 'Initial review',
      lawyer_review: 'Lawyer review',
      documents_required: 'Documents required',
      payment_pending: 'Payment pending',
      ready_to_file: 'Ready to file',
      submitted: 'Submitted',
      approved: 'Approved',
      rejected: 'Rejected',
      closed: 'Closed',
    },
    outcomes: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      withdrawn: 'Withdrawn',
      expired: 'Expired',
      renewed: 'Renewed',
    },
    paymentStatuses: {
      not_needed: 'Not needed',
      pending: 'Pending',
      requested: 'Requested',
      paid: 'Paid',
      waived: 'Waived',
    },
    paymentMilestones: {
      consultation: 'Consultation',
      case_opening: 'Case opening',
      filing: 'Filing',
      renewal: 'Renewal',
    },
    nomadPage: {
      title: 'Nomad for Spain',
      subtitle:
        'We split Nomad into three separate processes so immigrants and lawyers do not mix requirements, payments, or documents.',
      cards: {
        nomad_holder: 'I am the main applicant',
        nomad_family: 'I want to open a family case',
        nomad_renewal: 'I need to renew a Nomad case',
      },
      summaryTitle: 'Why these are separate processes',
      summaryBullets: [
        'Main applicant: foreign company relationship, core eligibility, and the base case.',
        'Family members: relationship and dependency proof, with their own documents and payments.',
        'Renewal: a new linked case, never just a status change inside the original one.',
      ],
      holderTitle: 'Main applicant',
      holderBullets: [
        'Full passport, fee, and application form.',
        'At least 3 months of employment or professional relationship.',
        'Foreign company with at least 1 year of real ongoing activity.',
        'Letter authorizing remote work from Spain.',
        'Enough income, degree or 3 years of experience, social security or insurance, and criminal record proof.',
      ],
      familyTitle: 'Family members',
      familyBullets: [
        'Spouse/partner, children, or dependent ascendants with documentary proof of the relationship.',
        'Economic or physical dependency proof where required.',
        'Financial sufficiency linked to the main holder.',
        'A separate case so documents, payments, and status do not contaminate the main file.',
      ],
      renewalTitle: 'Renewal',
      renewalBullets: [
        'Opened as a new case linked to the prior approved or active Nomad case.',
        'Must prove continuity of the qualifying relationship, sufficient resources, and ongoing compliance.',
        'Useful when the user needs a fresh filing package, new payment stage, or a different legal strategy.',
      ],
      faqTitle: 'Operational rules the product should surface',
      faqBullets: [
        'In a professional relationship, Spanish clients cannot exceed 20% of total professional activity.',
        'In an employment relationship, the work remains tied to the foreign employer.',
        'Family members may obtain their own authorization and work in Spain if they qualify.',
      ],
      sources: ministrySources,
    },
    immigrantDashboard: {
      title: 'Your cases',
      subtitle: 'Manage multiple processes without losing prior history.',
      activeCases: 'Active cases',
      pastCases: 'Past cases',
      noCases: "You haven't opened any case yet.",
      noCasesBody: 'Start with main applicant, family members, or renewal.',
      startNewCase: 'Start a new case',
      openCases: 'View cases',
      documents: 'Recent documents',
      pendingRequest: 'Lawyer request',
    },
    immigrantCases: {
      title: 'My cases',
      subtitle: 'Each case has its own lawyer, payments, documents, and timeline.',
      openNew: 'Create new case',
      activeSection: 'Active',
      archivedSection: 'History',
      emptyActive: 'You have no active cases.',
      emptyArchived: 'No resolved or closed cases yet.',
      viewCase: 'View case',
      relatedTo: 'Linked to',
      lawyerPending: 'No lawyer assigned yet',
    },
    newCase: {
      title: 'Create new case',
      subtitle: 'Choose the right international telework process and open an independent file.',
      trackLabel: 'Case type',
      summaryLabel: 'Case context',
      summaryPlaceholder:
        'Example: previous student attempt was rejected, now I want to apply as an international remote worker.',
      linkedCaseLabel: 'Linked case',
      linkedCasePlaceholder: 'Select a prior case when relevant',
      submit: 'Create case',
      creating: 'Creating case...',
      success: 'Case created successfully.',
      error: 'The case could not be created.',
    },
    caseDetail: {
      overview: 'Overview',
      documents: 'Documents',
      payments: 'Payments',
      timeline: 'History',
      opened: 'Opened',
      lawyer: 'Lawyer',
      linkedHistory: 'Linked history',
      requestLawyer: 'Choose a lawyer for this case',
      noLawyer: 'No lawyer assigned yet',
      noDocuments: 'No documents in this case yet.',
      noPayments: 'No payment milestones yet.',
      noEvents: 'No timeline events yet.',
      relatedCase: 'Linked case',
      sourceCase: 'Source case',
      deleteCase: 'Delete case',
      deleting: 'Deleting case...',
      deleteConfirm: 'Are you sure you want to delete this case? Its documents, payments, and history will also be removed.',
      deleteError: 'The case could not be deleted.',
      privateNotes: 'Private notes',
      privateNotesPlaceholder: 'Add a lawyer-only note for this case...',
      saveNote: 'Save note',
      savingNote: 'Saving note...',
      noPrivateNotes: 'No private notes yet.',
    },
    lawyerDashboard: {
      title: 'Practice cases',
      subtitle: 'Work is now organized around cases, not only people.',
      assignedCases: 'Assigned cases',
      pendingRequests: 'Pending requests',
      readyToFile: 'Ready to file',
      recentCases: 'Recent cases',
    },
    lawyerCases: {
      title: 'Cases',
      subtitle: 'Manage main applicant, family, and renewal workflows independently.',
      empty: 'You do not have assigned cases.',
      caseOwner: 'Client',
      stage: 'Stage',
      track: 'Track',
      opened: 'Opened',
      viewCase: 'Open case',
    },
    lawyerRequests: {
      caseLabel: 'Case',
      linkedTrack: 'Requested track',
    },
  },
  pt: {
    categories: {
      eyebrow: 'Autorizações UGE',
      title: 'Categorias oficiais para viver e trabalhar na Espanha',
      subtitle:
        'Mostramos as vias oficiais da Unidade de Grandes Empresas. Nomad já está detalhada; as demais ficam visíveis para orientar o usuário.',
      availableNow: 'Disponível agora',
      comingSoon: 'Em breve',
      exploreNomad: 'Explorar Nomad',
      cards: {
        entrepreneurs: { title: 'Empreendedores', description: 'Para projetos empresariais inovadores com interesse econômico para a Espanha.' },
        highly_qualified: { title: 'Profissionais altamente qualificados', description: 'Para contratação especializada e cartão azul UE.' },
        researchers: { title: 'Pesquisadores', description: 'Para I&D e mobilidade de pesquisa.' },
        ict: { title: 'Mobilidade intraempresarial', description: 'Transferências internacionais dentro do mesmo grupo empresarial.' },
        collective_ict: { title: 'ICT coletiva', description: 'Procedimento coletivo para grupos de transferências intraempresariais.' },
        audiovisual: { title: 'Audiovisual e cultural', description: 'Produções audiovisuais e atividades culturais estratégicas.' },
        nomad: { title: 'Nomad', description: 'Teletrabalho internacional com empregador ou clientes fora da Espanha.' },
        family: { title: 'Familiares', description: 'Permissões para familiares sob a Lei 14/2013 com regras de vínculo e dependência.' },
        legacy: { title: 'Caso legado', description: 'Caso migrado do modelo anterior da plataforma.' },
      },
    },
    tracks: {
      legacy_general: { title: 'Caso legado', shortTitle: 'Legado', description: 'Migrado do modelo anterior do produto.' },
      nomad_holder: { title: 'Teletrabalho internacional - requerente principal', shortTitle: 'Principal', description: 'Pedido inicial da pessoa titular que trabalha à distância para empresa ou clientes fora de Espanha.' },
      nomad_family: { title: 'Teletrabalho internacional - familiares', shortTitle: 'Familiares', description: 'Caso separado para familiares do titular, com documentação e acompanhamento próprios.' },
      nomad_renewal: { title: 'Teletrabalho internacional - renovação', shortTitle: 'Renovação', description: 'Caso de renovação separado, ligado a uma autorização anterior de teletrabalho internacional.' },
    },
    caseStages: {
      intake: 'Abertura do caso',
      eligibility_check: 'Revisão inicial',
      lawyer_review: 'Revisão jurídica',
      documents_required: 'Documentos requeridos',
      payment_pending: 'Pagamento pendente',
      ready_to_file: 'Pronto para apresentar',
      submitted: 'Apresentado',
      approved: 'Aprovado',
      rejected: 'Rejeitado',
      closed: 'Encerrado',
    },
    outcomes: {
      pending: 'Pendente',
      approved: 'Aprovado',
      rejected: 'Rejeitado',
      withdrawn: 'Retirado',
      expired: 'Expirado',
      renewed: 'Renovado',
    },
    paymentStatuses: {
      not_needed: 'Não necessário',
      pending: 'Pendente',
      requested: 'Solicitado',
      paid: 'Pago',
      waived: 'Isento',
    },
    paymentMilestones: {
      consultation: 'Consulta',
      case_opening: 'Abertura do caso',
      filing: 'Protocolo',
      renewal: 'Renovação',
    },
    nomadPage: {
      title: 'Nomad para a Espanha',
      subtitle:
        'Dividimos Nomad em três processos separados para que imigrante e advogado não misturem requisitos, pagamentos ou documentos.',
      cards: {
        nomad_holder: 'Sou a pessoa solicitante principal',
        nomad_family: 'Quero abrir um caso para familiares',
        nomad_renewal: 'Preciso renovar um caso Nomad',
      },
      summaryTitle: 'Por que são processos separados',
      summaryBullets: [
        'Requerente principal: relação com empresa estrangeira, elegibilidade principal e caso base.',
        'Familiares: prova de vínculo e dependência, com documentos e pagamentos próprios.',
        'Renovação: novo caso vinculado, nunca apenas uma mudança de estado do caso original.',
      ],
      holderTitle: 'Requerente principal',
      holderBullets: [
        'Passaporte completo, taxa e formulário.',
        'Pelo menos 3 meses de relação laboral ou profissional.',
        'Empresa estrangeira com pelo menos 1 ano de atividade real e contínua.',
        'Carta autorizando o trabalho remoto a partir da Espanha.',
        'Renda suficiente, diploma ou 3 anos de experiência, segurança social ou seguro e antecedentes criminais.',
      ],
      familyTitle: 'Familiares',
      familyBullets: [
        'Cônjuge/companheiro, filhos ou ascendentes dependentes com prova documental do vínculo.',
        'Prova de dependência econômica ou física quando exigido.',
        'Recursos financeiros suficientes vinculados ao holder principal.',
        'Caso separado para que documentos, pagamentos e status não contaminem o processo principal.',
      ],
      renewalTitle: 'Renovação',
      renewalBullets: [
        'Aberto como novo caso vinculado ao Nomad anterior aprovado ou ativo.',
        'Deve demonstrar continuidade da relação qualificadora, recursos suficientes e cumprimento contínuo.',
        'Serve também quando o usuário precisa reorganizar documentos, novo pagamento ou estratégia jurídica diferente.',
      ],
      faqTitle: 'Regras operacionais que o produto deve mostrar',
      faqBullets: [
        'Na relação profissional, clientes espanhóis não podem superar 20% da atividade total.',
        'Na relação laboral, o trabalho continua vinculado ao empregador estrangeiro.',
        'Familiares podem obter autorização própria e trabalhar na Espanha se cumprirem os requisitos.',
      ],
      sources: ministrySources,
    },
    immigrantDashboard: {
      title: 'Seus casos',
      subtitle: 'Gerencie vários processos sem perder o histórico anterior.',
      activeCases: 'Casos ativos',
      pastCases: 'Casos anteriores',
      noCases: 'Você ainda não abriu nenhum caso.',
      noCasesBody: 'Comece com requerente principal, familiares ou renovação.',
      startNewCase: 'Criar novo caso',
      openCases: 'Ver casos',
      documents: 'Documentos recentes',
      pendingRequest: 'Pedido de advogado',
    },
    immigrantCases: {
      title: 'Meus casos',
      subtitle: 'Cada caso tem seu próprio advogado, pagamentos, documentos e linha do tempo.',
      openNew: 'Criar novo caso',
      activeSection: 'Ativos',
      archivedSection: 'Histórico',
      emptyActive: 'Você não tem casos ativos.',
      emptyArchived: 'Ainda não há casos encerrados ou resolvidos.',
      viewCase: 'Ver caso',
      relatedTo: 'Vinculado a',
      lawyerPending: 'Ainda sem advogado atribuído',
    },
    newCase: {
      title: 'Criar novo caso',
      subtitle: 'Escolha o processo correto de teletrabalho internacional e abra um caso independente.',
      trackLabel: 'Tipo de caso',
      summaryLabel: 'Contexto do caso',
      summaryPlaceholder:
        'Exemplo: tentativa anterior como estudante foi rejeitada e agora quero aplicar como teletrabalhador internacional.',
      linkedCaseLabel: 'Caso vinculado',
      linkedCasePlaceholder: 'Selecione um caso anterior quando fizer sentido',
      submit: 'Criar caso',
      creating: 'Criando caso...',
      success: 'Caso criado com sucesso.',
      error: 'Não foi possível criar o caso.',
    },
    caseDetail: {
      overview: 'Resumo',
      documents: 'Documentos',
      payments: 'Pagamentos',
      timeline: 'Histórico',
      opened: 'Aberto',
      lawyer: 'Advogado',
      linkedHistory: 'Histórico vinculado',
      requestLawyer: 'Escolher advogado para este caso',
      noLawyer: 'Ainda sem advogado atribuído',
      noDocuments: 'Ainda não há documentos neste caso.',
      noPayments: 'Ainda não há marcos de pagamento.',
      noEvents: 'Ainda não há eventos na linha do tempo.',
      relatedCase: 'Caso vinculado',
      sourceCase: 'Caso de origem',
      deleteCase: 'Eliminar caso',
      deleting: 'A eliminar caso...',
      deleteConfirm: 'Tem a certeza de que quer eliminar este caso? Os documentos, pagamentos e histórico também serão removidos.',
      deleteError: 'Não foi possível eliminar o caso.',
      privateNotes: 'Notas privadas',
      privateNotesPlaceholder: 'Adicione uma nota visível apenas para o advogado neste caso...',
      saveNote: 'Guardar nota',
      savingNote: 'A guardar nota...',
      noPrivateNotes: 'Ainda não existem notas privadas.',
    },
    lawyerDashboard: {
      title: 'Casos do escritório',
      subtitle: 'O trabalho agora é organizado por caso, não apenas por pessoa.',
      assignedCases: 'Casos atribuídos',
      pendingRequests: 'Pedidos pendentes',
      readyToFile: 'Prontos para protocolar',
      recentCases: 'Casos recentes',
    },
    lawyerCases: {
      title: 'Casos',
      subtitle: 'Gerencie requerente principal, familiares e renovação de forma independente.',
      empty: 'Você não tem casos atribuídos.',
      caseOwner: 'Cliente',
      stage: 'Etapa',
      track: 'Track',
      opened: 'Aberto',
      viewCase: 'Abrir caso',
    },
    lawyerRequests: {
      caseLabel: 'Caso',
      linkedTrack: 'Track solicitado',
    },
  },
} as const

export function getCaseContent(locale: Locale = defaultLocale) {
  return content[locale] || content[defaultLocale]
}
